include:
  - project: 'vcsuite/npm/vcmap/ui'
    ref: main
    file:
      - 'templates/.plugin-v1.yml'
      - 'templates/.plugin-ts-v1.yml'
      - 'templates/.publish-package-v1.yml'
      - 'templates/.publish-npm-internal-v1.yml'
